import type { WorksheetTemplate, WorksheetTemplateId } from "@/types/obrasci";

const STANDARD_CLINIC_DIETS = [
  "DIJABETIČNA DIJETA (1-6R)",
  "LAGANA HIPERPROTEINSKA DIJETA (1-6R)",
  "HIPERPROTEINSKA DIJETA (1-6R)",
  "GLUTEN FREE DIJETA (1-6R)",
  "HEMODIJALIZA NESLANA DIJETA (1-6R)",
  "DIJAREJA MIX 1 DIJETA (1-2R)",
  "DIJAREJA 2 DIJETA (1-2R)",
  "INDIVIDUALNO PRILAGOĐENA (1-R)",
  "OPŠTA - V",
];

const I_HIRURSKA_DIETS = [
  "DIJABETIČNA LAGANA DIJETA (1-6D)",
  "DIJAREJA 2 DIJETA (1-2D)",
  "TEČNO KAŠASTA DIJETA (1-D)",
  "KAŠASTA 1 DIJETA (1-2D)",
  "DIJABETIČNA KAŠA DIJETA (1-2D)",
  "IN. PRILAGOĐENA LAGANA PRELAZNA (1-6D)",
  "IN. PRILAGOĐENA PANKREATIČNA DIJETA (1-6D)",
  "IN. PRILAGOĐENA NA POSTOPERATIVNA (1-6D)",
  "INDIVIDUALNO PRILAGOĐENI (1-D)",
  "OPŠTA H-V",
  "KISELO MLEKO - DORUČAK, VEČERA",
  "KUVANO JAJE *2 KOM* - DORUČAK, VEČERA",
  "MLADI SIR 100g porcija - DORUČAK, VEČERA",
  "BISTRA SUPA BEZ TESTENINE por. 200ml - RUČAK",
  "BARENO PILEĆE BELO MESO por. 150g - RUČAK",
  "KROMPIR PIRE NA VODI por. 100g - RUČAK",
];

const JELOVNIK_DIETS = [
  "OPŠTA DIJETA (1-6D)",
  "DIJABETIČNA LAGANA DIJETA (1-6D)",
  "DIJABETIČNA T-DIJETA (1-D)",
  "DIJABETIČNA KAŠA DIJETA (1-2D)",
  "TEČNO KAŠASTA DIJETA (1-D)",
  "KAŠASTA 1 DIJETA (1-2D)",
  "KAŠASTA 2 DIJETA (1-2D)",
  "DIJAREJA MIX 1 DIJETA (1-2D)",
  "LAGANA HIPERPROTEINSKA DIJETA*** (1-6D)",
  "HIPERPROTEINSKA DIJETA (1-6D)",
  "HEMODIJALIZA NESLANA DIJETA (1-6R)",
  "TEČNA DIJETA",
  "STROGA DIJETA",
  "OPŠTA H-V",
  "DIJAREJA 2 DIJETA (1-2D)",
  "DIJABETIČNA REDUKCIONA DIJETA 1200 kcal (1-6D)",
  "IN. PRILAGOĐENA LAGANA PRELAZNA (1-6D)",
  "IN. PRILAGOĐENA PANKREATIČNA DIJETA (1-6D)",
  "POSNA DIJETA",
  "VEGETERIJANSKA DIJETA",
  "HIPERPROTEINSKA POSNA DIJETA",
  "IN. PRILAGOĐENA NA POSTOPERATIVNA (1-6D)",
  "INDIVIDUALNO PRILAGOĐENI (1-D)",
  "KORONARNA DIJETA BEZ SOLI (1-6D)",
  "Sonda 1 HIPERPROTEINSKA D - 1D",
  "Sonda 2 BEZGLUTENSKA D - 1D",
  "IN. PRILAGOĐENA LAGANA DIJETA BEZ LAKTOZE (1-6D)",
  "IN. PRILAGOĐENA ZA DIJABETIČARE BEZ LAKTOZE (1-6D)",
  "IN. PRILAGOĐENA BEZ LAKTOZE BEZ ML. SIRA (1-6D)",
];

const SPECIJALCI_SECTIONS = [
  {
    id: "main",
    title: "",
  },
  {
    id: "ostale-klinike",
    title: "SPECIJALNE DIJETE - OSTALE KLINIKE",
  },
  {
    id: "interna-a",
    title: "SPECIJALNE DIJETE - INTERNA A",
    printBreakBefore: true,
  },
  {
    id: "prva-hirurska",
    title: "SPECIJALNE DIJETE - PRVA HIRURŠKA",
  },
];

const SPECIJALCI_DIETS = [
  {
    sectionId: "main",
    specialDiet: "DIJABETIČNA TEČNO KAŠASTA",
    floor: "0, 1, 6, 7, 9",
    mealCount: "5",
    mainMeal: "PIRE KROMPIR SA VOM 250G",
    bread: "",
    warmSupplement: "ČAJ 250ml",
    coldSupplement: "",
    snack: "UŽINA 2",
  },
  {
    sectionId: "main",
    specialDiet: "INDIV. HIPER (5 obroka od 0-1500g)\nNestrović Radojka",
    floor: "0",
    mealCount: "1",
    mainMeal: "MUSAKA OD KARFIOLA 200g; SVEŽA PARADAJZ SALATA 100g",
    bread: "BELI HLEB 60g",
    warmSupplement: "",
    coldSupplement: "GRČKI JOGURT 180g",
    snack: "PROTEINSKI PUDING 200g",
  },
  {
    sectionId: "main",
    specialDiet: "INDIV. HEPATIČNA (EV=3000kcal)\nJevtić Nenad",
    floor: "0",
    mealCount: "1",
    mainMeal: "NESLANA PROJA SA SIROM 250g",
    bread: "",
    warmSupplement: "",
    coldSupplement: "JOGURT 180ml",
    snack: "PIRE OD JABUKA SA KJEKSOM 200g",
  },
  {
    sectionId: "main",
    specialDiet: "INDIV. DM SONDA (5 obroka od 320ml)\nĐorđević Nenad",
    floor: "0",
    mealCount: "1",
    mainMeal: "SONDA OD POVRĆA SA PILETINOM 300ml (piletina 50g, povrće 100g, ulje, so)",
    bread: "",
    warmSupplement: "",
    coldSupplement: "",
    snack: "",
  },
  {
    sectionId: "main",
    specialDiet:
      "IP. DM HEPATIČNA SONDA (EV=1800kcal, 5 obroka od 320ml)\nŠehić Zvezdan",
    floor: "1",
    mealCount: "1",
    mainMeal:
      "SONDA OD POVRĆA 300ml (pasirani sir 80g, pirinač 100g, šargarepa 100g, so) / tečna kaša (povrće, šargarepa, pirinač, krompir sa obranim mlekom 180g)",
    bread: "",
    warmSupplement: "ČAJ 250ml",
    coldSupplement: "",
    snack: "",
  },
  {
    sectionId: "main",
    specialDiet: "INDIV. SONDA (5 obroka od 320ml/0-1500ml)\nĐukanović Rajko",
    floor: "1",
    mealCount: "1",
    mainMeal:
      "SONDA OD POVRĆA SA ĆURETINOM 350g (ćureći file 100g, pirinač 20g, slatka paprika, tikvica, šargarepa, praziluk, so, biljno ulje) / čaj sa piškotama sa vanilijom ili čaj bez vode",
    bread: "",
    warmSupplement: "",
    coldSupplement: "",
    snack: "",
  },
  {
    sectionId: "main",
    specialDiet: "IP. DM HIPER, KCAL\nArsenijević Milan",
    floor: "1",
    mealCount: "1",
    mainMeal: "PROJA SA HELJDOM, SIROM I SEMENKAMA 250g",
    bread: "",
    warmSupplement: "",
    coldSupplement: "KISELO MLEKO 180ml",
    snack: "JOGURT 180ml, INT. KIFLA 80g",
  },
  {
    sectionId: "main",
    specialDiet:
      "INDIV. DM KAŠASTA (seckalica i sitno seckano)\nRadovanović Radmila",
    floor: "1",
    mealCount: "1",
    mainMeal:
      "DINSTANA MLEVENA PILETINA 150g; KAŠA OD POVRĆA 200g (karfiol 100g, krompir 100g, tikvica 70g, maslinovo ulje 10ml, so)",
    bread: "",
    warmSupplement: "",
    coldSupplement: "GRČKI JOGURT 180ml",
    snack: "PUDING 200g",
  },
  {
    sectionId: "main",
    specialDiet: "INDIV. DM SONDA (5 obroka od 320ml)\nDimić Zoran",
    floor: "1",
    mealCount: "1",
    mainMeal: "SONDA OD POVRĆA SA PILETINOM 300ml (ćureći file, povrće, ulje, so)",
    bread: "",
    warmSupplement: "",
    coldSupplement: "JOGURT 180ml",
    snack: "",
  },
  {
    sectionId: "ostale-klinike",
    specialDiet: "INDIV. PRILAGOĐENA\nSrejović Aleksandar",
    floor: "4",
    mealCount: "1",
    mainMeal: "UROLANA PILETINA 150g; MLAĐI SIR 50g; PEČENI KROMPIR 200g",
    bread: "BELI HLEB 60g",
    warmSupplement: "ČAJ 250ml",
    coldSupplement: "",
    snack: "",
  },
  {
    sectionId: "ostale-klinike",
    specialDiet:
      "INDIV. LIP*** (bez vidljivih masnoća - pečen/kuvan)\nBrimković Marica",
    floor: "4",
    mealCount: "1",
    mainMeal: "MLAĐI SIR 100g; PEČENI KROMPIR 200g (bez dodate masti)",
    bread: "BELI HLEB 60g",
    warmSupplement: "ČAJ 250ml",
    coldSupplement: "",
    snack: "",
  },
  {
    sectionId: "ostale-klinike",
    specialDiet: "INDIV. NESLANA BMP",
    floor: "9",
    mealCount: "1",
    mainMeal: "HUMUS NAMAZ 150g; NESLANI PEČENI KROMPIR 200g",
    bread: "INTEGRALNI HLEB 60g",
    warmSupplement: "ČAJ 250ml",
    coldSupplement: "",
    snack: "",
  },
  {
    sectionId: "ostale-klinike",
    specialDiet: "INDIV. DIJABETIČNA\nJura Rajmentina",
    floor: "10",
    mealCount: "1",
    mainMeal: "PROJA SA HELJDOM, SIROM I SEMENKAMA 250g",
    bread: "INTEGRALNI HLEB 70g",
    warmSupplement: "",
    coldSupplement: "KIGL - 3-MEKO; TEČNI JOGURT 180ml",
    snack: "SVEŽI KIVI 150g",
  },
  {
    sectionId: "ostale-klinike",
    specialDiet: "INDIV. 800kcal",
    floor: "10",
    mealCount: "1",
    mainMeal: "PROJA SA HELJDOM, SIROM I SEMENKAMA 150g",
    bread: "",
    warmSupplement: "ČAJ 250ml",
    coldSupplement: "",
    snack: "",
  },
  {
    sectionId: "ostale-klinike",
    specialDiet: "INDIV. 1000kcal",
    floor: "11",
    mealCount: "1",
    mainMeal: "PROJA SA HELJDOM, SIROM I SEMENKAMA 180g",
    bread: "",
    warmSupplement: "ČAJ 250ml",
    coldSupplement: "JOGURT 180ml",
    snack: "SEZONSKA SALATA 100g",
  },
  {
    sectionId: "ostale-klinike",
    specialDiet: "INDIV. 1200kcal",
    floor: "10",
    mealCount: "1",
    mainMeal: "PROJA SA HELJDOM, SIROM I SEMENKAMA 200g",
    bread: "",
    warmSupplement: "ČAJ 250ml",
    coldSupplement: "JOGURT 180ml",
    snack: "SEZONSKA SALATA 100g",
  },
  {
    sectionId: "ostale-klinike",
    specialDiet: "INDIV. BEZ MAHUNA\nFurundžija Živica",
    floor: "11",
    mealCount: "1",
    mainMeal: "MUSAKA OD KARFIOLA 250g",
    bread: "BELI HLEB 60g",
    warmSupplement: "",
    coldSupplement: "JOGURT 180ml",
    snack: "",
  },
  {
    sectionId: "interna-a",
    specialDiet: "INDIV. DIJABET DGL\nMilić Milovanović",
    floor: "KČ ZA ALERGIJU",
    mealCount: "1",
    mainMeal: "MLAĐI SIR 100g; PEČENI KROMPIR 200g",
    bread: "BELI HLEB 60g",
    warmSupplement: "",
    coldSupplement: "JOGURT 180ml",
    snack: "",
  },
  {
    sectionId: "interna-a",
    specialDiet: "INDIV. BGL I BMP\nJelena Milanković",
    floor: "KČ ZA ALERGIJU",
    mealCount: "1",
    mainMeal: "KUVANI TOFU SA SIROM 150g; PEČENI KROMPIR 200g",
    bread: "BELI HLEB 60g",
    warmSupplement: "",
    coldSupplement: "JOGURT 180ml",
    snack: "",
  },
  {
    sectionId: "interna-a",
    specialDiet: "INDIV. LIP***\nSofija Pejin",
    floor: "KČ ZA REUMATOL.",
    mealCount: "1",
    mainMeal: "PROJA SA SIROM 250g",
    bread: "",
    warmSupplement: "",
    coldSupplement: "KISELO MLEKO 180ml",
    snack: "2x PEČENA JABUKA",
  },
  {
    sectionId: "interna-a",
    specialDiet: "INDIV. LIP*** KAŠA\nAleksandra Ivić",
    floor: "KČ ZA REUMATOL.",
    mealCount: "1",
    mainMeal: "DINSTANA MLEVENA PILETIN 200g; PIRE OD KROMPIRA I ŠARGAREPE 200g",
    bread: "BELI HLEB 60g",
    warmSupplement: "ČAJ 250ml",
    coldSupplement: "",
    snack: "",
  },
  {
    sectionId: "interna-a",
    specialDiet: "INDIV. DIJAREJA 2 MIX + DODACI\nMarija Cvetić",
    floor: "KČ ZA REUMATOL.",
    mealCount: "1",
    mainMeal:
      "BEZ KUVANOG KROMPIRA + SLAN SER 100g / PIRINAČ SA ŠARGAREPOM 200g",
    bread: "",
    warmSupplement: "PIRINČANA VODA 250ml; T-BLOK",
    coldSupplement: "",
    snack: "ČAJ 250ml; PIRE OD JABUKA 200g",
  },
  {
    sectionId: "prva-hirurska",
    specialDiet: "INDIV. PRT/K3DL DOKTOR ZA KANDIDU\nMilivoje Stojanović",
    floor: "0",
    mealCount: "1",
    mainMeal:
      "DINSTANA MLEVENA PILETINA / LAGANOM SOSU 120g; KAŠA OD POVRĆA 200g (tikvica, krompir, šargarepa, maslinovo ulje, so)",
    bread: "TONUS HLEB 60g",
    warmSupplement: "ČAJ 250ml",
    coldSupplement: "",
    snack: "",
  },
];

const CLINICAL_DIET_COLUMNS: WorksheetTemplate["columns"] = [
  { id: "diet", label: "DIJETA", width: "42%" },
  {
    id: "alergologija",
    label: "ALERGOLOGIJA",
    width: "16%",
    inputType: "number",
    nowrap: true,
  },
  {
    id: "hematologija",
    label: "HEMATOLOGIJA",
    width: "16%",
    inputType: "number",
    nowrap: true,
  },
  {
    id: "total",
    label: "UKUPNO OBROKA PO DIJETAMA",
    width: "20%",
    inputType: "computed",
    computedFrom: ["alergologija", "hematologija"],
  },
];

const I_HIRURSKA_COLUMNS: WorksheetTemplate["columns"] = [
  { id: "diet", label: "DIJETA", width: "62%" },
  {
    id: "iHiruska",
    label: "BROJ OBROKA",
    width: "16%",
    inputType: "number",
    nowrap: true,
  },
  {
    id: "total",
    label: "UKUPNO OBROKA PO DIJETAMA",
    width: "22%",
    inputType: "computed",
    computedFrom: ["iHiruska"],
  },
];

const JELOVNIK_COLUMNS: WorksheetTemplate["columns"] = [
  { id: "dietName", label: "NAZIV DIJETE", width: "20%" },
  { id: "mainMeal", label: "GLAVNI OBROK", width: "40%" },
  { id: "bread", label: "HLEB", width: "10%", inputType: "compact-text" },
  {
    id: "warmSupplement",
    label: "TOPLI DODATAK",
    width: "10%",
    inputType: "compact-text",
  },
  {
    id: "coldSupplement",
    label: "HLADNI DODATAK",
    width: "10%",
    inputType: "compact-text",
  },
  { id: "snack", label: "UŽINA", width: "10%", inputType: "compact-text" },
];

const SPECIJALCI_COLUMNS: WorksheetTemplate["columns"] = [
  { id: "specialDiet", label: "NAZIV SPECIJALNE DIJETE", width: "20%" },
  { id: "floor", label: "SPRAT", width: "7%", inputType: "compact-text" },
  { id: "mealCount", label: "BR. OBROKA", width: "7%", inputType: "number" },
  { id: "mainMeal", label: "GLAVNI OBROK", width: "36%" },
  { id: "bread", label: "HLEB", width: "8%", inputType: "compact-text" },
  {
    id: "warmSupplement",
    label: "TOPLI DODATAK",
    width: "7%",
    inputType: "compact-text",
  },
  {
    id: "coldSupplement",
    label: "HLADNI DODATAK",
    width: "7%",
    inputType: "compact-text",
  },
  { id: "snack", label: "UŽINA", width: "8%", inputType: "compact-text" },
];

const CLINICAL_DIET_DEFAULT_ROWS = STANDARD_CLINIC_DIETS.map((diet) => ({
  diet,
  alergologija: "",
  hematologija: "",
}));

const I_HIRURSKA_DEFAULT_ROWS = I_HIRURSKA_DIETS.map((diet) => ({
  diet,
  iHiruska: "",
}));

const JELOVNIK_DEFAULT_ROWS = JELOVNIK_DIETS.map((dietName) => ({
  dietName,
  mainMeal: "",
  bread: "",
  warmSupplement: "",
  coldSupplement: "",
  snack: "",
}));

const SPECIJALCI_DEFAULT_ROWS = SPECIJALCI_DIETS.map((diet) => ({ ...diet }));

export const WORKSHEET_TEMPLATES: WorksheetTemplate[] = [
  {
    id: "daily-order",
    title: "INTERNA A",
    selectorLabel: "Interna A",
    subtitle: "Operativni nalog za proizvodnju i distribuciju obroka.",
    documentPrefix: "DN",
    initialRowCount: CLINICAL_DIET_DEFAULT_ROWS.length,
    columns: CLINICAL_DIET_COLUMNS,
    defaultRows: CLINICAL_DIET_DEFAULT_ROWS,
  },
  {
    id: "special-regimes",
    title: "SPECIJALCI",
    selectorLabel: "Specijalni Režimi Ishrane",
    subtitle: "Evidencija posebnih režima, pacijenata i izmena po obrocima.",
    documentPrefix: "SR",
    initialRowCount: SPECIJALCI_DEFAULT_ROWS.length,
    columns: SPECIJALCI_COLUMNS,
    defaultRows: SPECIJALCI_DEFAULT_ROWS,
    sections: SPECIJALCI_SECTIONS,
  },
  {
    id: "menus-normatives",
    title: "JELOVNIK",
    selectorLabel: "Jelovnik",
    subtitle: "Plan jelovnika i normativa za pripremu obroka.",
    documentPrefix: "JN",
    initialRowCount: JELOVNIK_DEFAULT_ROWS.length,
    columns: JELOVNIK_COLUMNS,
    defaultRows: JELOVNIK_DEFAULT_ROWS,
    printBreakAfterRowIndex: 13,
  },
  {
    id: "stock-issuance",
    title: "I HIRURŠKA",
    selectorLabel: "I Hirurška",
    subtitle: "Radni nalog za trebovanje namirnica iz magacina.",
    documentPrefix: "IZ",
    initialRowCount: I_HIRURSKA_DEFAULT_ROWS.length,
    columns: I_HIRURSKA_COLUMNS,
    defaultRows: I_HIRURSKA_DEFAULT_ROWS,
  },
] satisfies WorksheetTemplate[];

export const DEFAULT_WORKSHEET_TEMPLATE_ID: WorksheetTemplateId = "daily-order";
